# Usage:
# export KITCHEN_LOCAL_YAML=.kitchen.docker.yml
#   This will use the platforms and driver from this file.
#   The suites from the main .kitchen.yml will be merged
#   Allowing us to not duplicate the suites in both files
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  # https://hub.docker.com/_/centos/
  - name: centos-6
  - name: centos-7

  # https://hub.docker.com/_/fedora/
  # https://github.com/portertech/kitchen-docker/issues/147
  # - name: fedora-20
  # - name: fedora-21
  # - name: fedora-22 # waiting for DNF support
