driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # https://github.com/chef/bento
  - name: centos-6.6
  - name: centos-7.1

  - name: fedora-21
  - name: fedora-22

suites:
  - name: default
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]

  - name: testing
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    excludes:
      - centos-6.6 # repo does not exist
    attributes:
      yum-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: true
          docker-experimental:
            managed: false

  - name: experimental
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    yum-docker:
      repos:
        docker-main:
          managed: false
        docker-testing:
          managed: false
        docker-experimental:
          managed: true
