driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # https://github.com/chef/bento
  - name: centos-6.6
  - name: centos-7.1

  - name: fedora-21
  # - name: fedora-22 # waiting for DNF support

suites:
<% %w(11 12).each do |version| %>
  - name: default_chef<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]

  - name: testing_chef<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    excludes:
      - centos-6.6 # repo does not exist
      - centos-6
    attributes:
      yum-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: true
          docker-experimental:
            managed: false

  - name: experimental_chef<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    excludes:
      - centos-7.1 # test fails as it cannot resolve docker-engine-selinux
      - fedora-21  # test fails as it cannot resolve docker-engine-selinux
    attributes:
      yum-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: false
          docker-experimental:
            managed: true
<% end %>
