driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  # https://hub.docker.com/_/centos/
  - name: centos-6
  - name: centos-7

  # https://hub.docker.com/_/fedora/
  # https://github.com/portertech/kitchen-docker/issues/147
  - name: fedora-20
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]

  - name: testing
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    excludes:
      - centos-6 #repo does not exist
    attributes:
      yum-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: true
          docker-experimental:
            managed: false

  - name: experimental
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-docker]
      - recipe[test::install_docker]
    attributes:
      yum-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: false
          docker-experimental:
            managed: true
